import random

words = ['abacus', 'abandon', 'abattoir', 'abbreviation', 'abdicate', 'abdomen', 'abduct', 'aberrant', 'abeyance',
         'abhorrent', 'abject', 'abjure', 'ablution', 'abnegation', 'abnormal', 'abolition', 'abominable', 'abominate',
         'aboriginal', 'abortive', 'abound', 'abracadabra', 'abrade', 'abrasion', 'abridge', 'abridgment', 'abrogate',
         'abscond', 'absinth', 'absolution', 'abstain', 'abstemious', 'abstract', 'abstracted', 'abstruse', 'absurd',
         'absurdity', 'abundance', 'abysmal', 'accede', 'accelerate', 'accentuate', 'access', 'accessible',
         'accidental', 'acclaim', 'acclamation', 'acclivity', 'accolade', 'accommodating', 'accomplice', 'accord',
         'accordion', 'accoutrements', 'accretion', 'accrue', 'accumulate', 'acerbity', 'acidulous', 'acolyte',
         'acoustic', 'acoustics', 'acquaintance', 'acquiesce', 'acquiescent', 'acquired', 'acquisitive', 'acquittal',
         'acrimonious', 'acrimony', 'acrobat', 'acronym', 'activate', 'acumen', 'adagio', 'adamant', 'adaptable',
         'addendum', 'addiction', 'addictive', 'addled', 'adduce', 'adhere', 'adherent', 'adjacent', 'adjudicate',
         'adjure', 'adjutant', 'ad-lib', 'admonish', 'admonitory', 'adorable', 'adoration', 'adornment', 'adroit',
         'adulate', 'adulterate', 'adumbrate', 'advent', 'adversary', 'adversity', 'advisable', 'advisory',
         'aeronautics', 'aesthete', 'aesthetics', 'affable', 'affectation', 'affected', 'affection', 'affectionate',
         'affidavit', 'affiliate', 'affiliation', 'affinity', 'affirmative', 'affliction', 'affront', 'aficionado',
         'aftermath', 'agenda', 'agglomerate', 'aggrandize', 'aggravate', 'aggregate', 'aggregation', 'aggressive',
         'aggrieved', 'aghast', 'agitated', 'agitation', 'agnostic', 'agreement', 'agronomist', 'ailment', 'airborne',
         'airtight', 'alabaster', 'alchemy', 'alcove', 'alienated', 'alkali', 'allegation', 'allegiance', 'allegro',
         'allergic', 'allergy', 'alleviate', 'alligator', 'allocation', 'allopathy', 'allude', 'allure', 'allurement',
         'allusion', 'alluvial', 'almond', 'alteration', 'altercation', 'altruism', 'aluminium', 'amalgam',
         'amalgamate', 'amateurish', 'ambidextrous', 'ambiguity', 'ambiguous', 'ambivalence', 'ambivalent', 'ambrosia',
         'ambush', 'amenable', 'amendment', 'amenity', 'amethyst', 'amiable', 'amicable', 'amnesia', 'amnesty',
         'amoral', 'amorous', 'amorphous', 'amortize', 'amplify', 'amputate', 'amulet', 'anachronism', 'analgesic',
         'analogous', 'analogy', 'anarchic', 'anarchy', 'anathema', 'anchorite', 'ancillary', 'anecdote', 'anemia',
         'anesthetic', 'anguish', 'anguished', 'animadvert', 'animation', 'animosity', 'animus', 'annihilate',
         'annotate', 'annotation', 'anodyne', 'anomalous', 'anomaly', 'anonymity', 'anonymous', 'anorexia',
         'antagonism', 'antagonist', 'antecedence', 'antedate', 'antediluvian', 'antenna', 'anterior', 'anthem',
         'anthology', 'anthropoid', 'anthropology', 'antibiotic', 'antibody', 'anticipate', 'anticipatory', 'antics',
         'antidote', 'antigen', 'antiquated', 'antiseptic', 'antithesis', 'antithetic', 'antler', 'apathetic', 'apathy',
         'aperitif', 'aperture', 'aphasia', 'aphorism', 'apiary', 'apiculture', 'aplomb', 'apocalyptic', 'apocrypha',
         'apocryphal', 'apogee', 'apologetic', 'apology', 'apoplectic', 'apostasy', 'apostate', 'apostrophe',
         'apotheosis', 'appalling', 'apparel', 'apparition', 'appeal', 'appealing', 'appease', 'appeasement',
         'appellation', 'appendage', 'appetite', 'appetizing', 'applicable', 'apposite', 'appreciable', 'appreciative',
         'apprehend', 'apprehension', 'apprehensive', 'apprise', 'approachable', 'approbation', 'approbatory',
         'appropriate', 'appropriation', 'approximate', 'aquatic', 'aqueduct', 'aquiline', 'arabesque', 'arable',
         'arbiter', 'arbitrary', 'arbitrate', 'arbitrator', 'arboreal', 'arboretum', 'arcane', 'archaeology', 'archer',
         'archetype', 'archipelago', 'archives', 'ardent', 'arduous', 'aristocrat', 'arithmetic', 'armada', 'armistice',
         'aromatic', 'arraign', 'arrears', 'arrogance', 'arrogant', 'arrogate', 'arsenic', 'arsonist',
         'arteriosclerosis', 'arthritis', 'articulate', 'artifice', 'artillery', 'artless', 'ascend', 'ascendancy',
         'ascent', 'ascertain', 'ascetic', 'asceticism', 'aseptic', 'asinine', 'asparagus', 'asperity', 'aspersion',
         'asphalt', 'asphyxia', 'asphyxiate', 'aspirant', 'aspiration', 'assail', 'assault', 'assent', 'assert',
         'assertive', 'asseverate', 'assiduity', 'assiduous', 'assimilate', 'assuage', 'assurance', 'assured', 'asthma',
         'astigmatic', 'astigmatism', 'astray', 'astringent', 'astrolabe', 'astrology', 'astute', 'asunder', 'asylum',
         'asymmetric', 'atheism', 'athletics', 'atonal', 'atonement', 'atrocious', 'atrocity', 'atrophy', 'attainment',
         'attentive', 'attenuate', 'attest', 'attire', 'attorney', 'attribute', 'attribution', 'attrition', 'attune to',
         'auction', 'audacious', 'audacity', 'audition', 'auditory', 'augment', 'augmentation', 'augury', 'auricular',
         'aurora', 'auspices', 'auspicious', 'austere', 'austerity', 'authentic', 'authenticate', 'authoritative',
         'authorization', 'authorize', 'autism', 'autocracy', 'autocrat', 'automatism', 'autonomous', 'autonomy',
         'autopsy', 'auxiliary', 'avalanche', 'avant-garde', 'avarice', 'avaricious', 'avenge', 'averse', 'aversion',
         'aviary', 'avocation', 'avowal', 'avuncular', 'awe-inspiring', 'awning', 'axiomatic', 'babble', 'bacchanal',
         'bacchanalian', 'backlog', 'bacteria', 'badger', 'badinage', 'baffle', 'baffling', 'bagatelle', 'balderdash',
         'baleful', 'ballad', 'ballast', 'ballerina', 'ballroom', 'ballyhoo', 'bamboozle', 'banality', 'baneful',
         'banish', 'banister', 'bankrupt', 'bankruptcy', 'banner', 'banter', 'barbarity', 'barbarous', 'barbecue',
         'barbed', 'barometer', 'baroque', 'barque', 'barrage', 'barren', 'barricade', 'barrier', 'barter', 'bashful',
         'bassoon', 'bauble', 'bauxite', 'bazaar', 'beacon', 'beater', 'beatific', 'beatitude', 'beaver', 'bedlam',
         'bedraggled', 'begrudge', 'beguile', 'beguiling', 'behold', 'beholder', 'belabour', 'beleaguer', 'belittle',
         'bellicose', 'belligerent', 'belongings', 'benediction', 'benefactor', 'beneficial', 'beneficiary',
         'benevolence', 'benevolent', 'benighted', 'benign', 'benignity', 'bequeath', 'bequest', 'berate', 'bereave',
         'bereft of', 'berserk', 'beseech', 'besiege', 'besmirch', 'bespeak', 'bestow', 'betray', 'beverage',
         'bibliography', 'bibulous', 'bicker', 'bifurcate', 'bigotry', 'bilingual', 'bilious', 'biosphere', 'bizarre',
         'blackmail', 'blanch', 'blandishments', 'blarney', 'blasphemous', 'blasphemy', 'blatant', 'bleachers',
         'blemish', 'blench', 'blight', 'blinds', 'blithe', 'blizzard', 'bloated', 'blockade', 'blockbuster', 'blotch',
         'blotto', 'blowhard', 'blunder', 'bodyguard', 'boggle', 'boisterous', 'bolster', 'bolted', 'bombast',
         'bombastic', 'bonanza', 'bonnet', 'boorish', 'booster', 'borough', 'botanical', 'botany', 'botulism',
         'boudoir', 'boulder', 'bounteous', 'bouquet', 'bovine', 'boycott', 'bracing', 'bravado', 'brawny', 'brazen',
         'breach', 'bridle', 'brilliant', 'brimful', 'brindled', 'broach', 'bromide', 'bronchitis', 'browse', 'brusque',
         'brutal', 'brutality', 'bubble', 'buckle', 'bucolic', 'buffoon', 'bullion', 'bulwark', 'bumble', 'bumper',
         'bumpkin', 'buoyancy', 'buoyant', 'bureaucracy', 'burgeon', 'burlesque', 'burnish', 'burrow', 'bushed',
         'buttress', 'bygone', 'byline', 'bypass', 'cachet', 'cacophony', 'cactus', 'cadaver', 'cadaverous', 'cajole',
         'calamitous', 'calamity', 'calcify', 'calcium', 'calculating', 'calibrate', 'calibre', 'calligraphy',
         'callous', 'callow', 'callus', 'calumniate', 'calumny', 'camouflage', 'campanology', 'canard', 'canary',
         'candela', 'candidature', 'canker', 'cannibal', 'cannibalism', 'canonical', 'canopy', 'cantankerous',
         'cantata', 'canyon', 'capacious', 'capacity', 'capitation', 'capitulate', 'capitulation', 'capricious',
         'captious', 'captivate', 'captivation', 'carapace', 'cardigan', 'careen', 'caribou', 'caricature', 'carnage',
         'carnation', 'carnival', 'carnivore', 'carnivorous', 'carousal', 'carouse', 'carrion', 'cartographer',
         'cascade', 'castigate', 'castigation', 'cataclysm', 'catalysis', 'catalyst', 'categorical', 'category',
         'caterpillar', 'catharsis', 'cathartic', 'cathode', 'catholic', 'caucus', 'caustic', 'cavalcade', 'cavalier',
         'cavalry', 'cavern', 'cavity', 'celebrated', 'celebrity', 'celerity', 'celestial', 'celibacy', 'celibate',
         'cellar', 'cemetery', 'censor', 'censorious', 'censorship', 'censure', 'centrifugal', 'centripetal',
         'cephalic', 'ceramics', 'cereal', 'cerebral', 'cerebration', 'cerebrum', 'cessation', 'cession', 'cetacean',
         'chagrin', 'chagrined', 'chameleon', 'chandelier', 'chaotic', 'chaperon', 'characterization', 'charades',
         'charisma', 'charismatic', 'charity', 'charlatan', 'charter', 'chassis', 'chaste', 'chasten', 'chastise',
         'chastity', 'chateau', 'chauvinism', 'checkmate', 'cheetah', 'chequer', 'chevron', 'chicanery', 'chimera',
         'chimerical', 'chinless', 'chipmunk', 'chiromancy', 'chivalrous', 'chivalry', 'choleric', 'choppy',
         'choreography', 'chortle', 'chorus', 'chromatic', 'chromosome', 'chronometer', 'chrysanthemum', 'chubby',
         'chuckle', 'chunky', 'churlish', 'cinder', 'cipher', 'circuitous', 'circumlocution', 'circumscribe',
         'circumspect', 'circumvent', 'cistern', 'civilian', 'civility', 'clairvoyance', 'clammy', 'clamorous',
         'clamour', 'clampdown', 'clandestine', 'clanger', 'clannish', 'clapper', 'clarification', 'clarity',
         'classification', 'classify', 'claustrophobia', 'cleavage', 'cleave', 'cleaver', 'clemency', 'clement',
         'clench', 'clientele', 'climacteric', 'clinch', 'clique', 'cloister', 'cloistered', 'closure', 'cloudburst',
         'cloying', 'clumsy', 'cluster', 'coagulant', 'coagulate', 'coalesce', 'coalition', 'cobbler', 'codicil',
         'coerce', 'coercion', 'coffer', 'cogency', 'cogent', 'cogitate', 'cogitation', 'cognate', 'cognomen',
         'coherent', 'cohesion', 'cohesive', 'coincide', 'coincidence', 'colander', 'collage', 'collate', 'collateral',
         'collation', 'collide', 'collision', 'colloquium', 'collude', 'collusion', 'colossal', 'colossus', 'coltish',
         'comatose', 'combustible', 'combustion', 'comely', 'commandment', 'commence', 'commencement', 'commend',
         'commendable', 'commensurate', 'commiserate', 'commitment', 'commodious', 'commodity', 'commotion', 'compact',
         'compassion', 'compassionate', 'compatibility', 'compatible', 'compel', 'compellation', 'compelling',
         'compendious', 'compendium', 'compensate', 'compere', 'compile', 'complacency', 'complacent', 'complaisance',
         'complaisant', 'complexion', 'compliance', 'compliant', 'compliment', 'complimentary', 'comply', 'comport',
         'comportment', 'composite', 'composure', 'comprehensive', 'compress', 'compressor', 'compromise', 'compulsion',
         'compulsive', 'compulsory', 'compunction', 'computation', 'compute', 'concatenate', 'concatenation', 'concave',
         'concede', 'conceit', 'conceited', 'conceivable', 'conceive', 'concerto', 'concession', 'conciliate',
         'conciliation', 'concise', 'concision', 'concoct', 'concoction', 'concomitant', 'concord', 'concordant',
         'concurrent', 'concussion', 'condemn', 'condemnation', 'condescend', 'condescension', 'condole with',
         'condolence', 'conduce to', 'conducive', 'confection', 'confide', 'configuration', 'confirmed', 'confiscate',
         'conflagration', 'conflate', 'confluence', 'confront', 'confrontation', 'congeal', 'congenial', 'congenital',
         'congest', 'congestion', 'conglomerate', 'congregate', 'congregation', 'congruent', 'congruity', 'conifer',
         'conjecture', 'conjugal', 'conjure', 'connivance', 'connive', 'connoisseur', 'connotation', 'connotative',
         'consanguinity', 'conscript', 'consequential', 'conservatory', 'consign', 'consignment', 'consolation',
         'console', 'consolidate', 'conspectus', 'conspicuous', 'conspiracy', 'conspirator', 'conspire',
         'constellation', 'consternation', 'constituent', 'construe', 'consummate', 'consummation', 'contagion',
         'contagious', 'contemplate', 'contemplation', 'contempt', 'contemptible', 'contention', 'contentious',
         'contiguity', 'contiguous', 'continence', 'continent', 'contingency', 'contingent', 'contort', 'contortion',
         'contract', 'contraction', 'contravene', 'contravention', 'contrite', 'contrition', 'contrive', 'contrived',
         'controversy', 'controvert', 'contumacious', 'contumacy', 'contumelious', 'contumely', 'contuse', 'conundrum',
         'convalesce', 'convalescence', 'conventionality', 'converge', 'conversant', 'conversion', 'convert',
         'convertible', 'convex', 'convict', 'conviction', 'convivial', 'convocation', 'convoke', 'convoluted',
         'convoy', 'convulse', 'convulsion', 'copious', 'copyright', 'coquetry', 'cordon', 'cornet', 'cornucopia',
         'corona', 'coronation', 'corporal', 'corporate', 'corpulence', 'corpulent', 'corpus', 'corpuscle', 'corral',
         'correlate', 'correspondent', 'corrigendum', 'corroborate', 'corroboration', 'corrugate', 'corrugation',
         'coruscate', 'cosmic', 'cosmos', 'cosset', 'costume', 'coterie', 'coterminous', 'cougar', 'countenance',
         'counteract', 'counterfeit', 'countermand', 'covenant', 'covert', 'covetous', 'cowardice', 'crabbed', 'crafty',
         'craggy', 'cramped', 'cranky', 'crater', 'cravat', 'craven', 'craving', 'crayon', 'crease', 'credence',
         'creditable', 'credulity', 'credulous', 'crepuscular', 'crescendo', 'crestfallen', 'crevice', 'cringe',
         'cringing', 'crinkle', 'cripple', 'crochet', 'cronyism', 'crooked', 'crossfire', 'crouch', 'crudity',
         'crumble', 'crumple', 'crunch', 'crusade', 'crustacean', 'cryptic', 'cryptogram', 'cubicle', 'cuddle',
         'cuirass', 'cuisine', 'culinary', 'culpable', 'cultivate', 'cumber', 'cumbersome', 'cupidity', 'curator',
         'curdle', 'curmudgeon', 'currish', 'cursive', 'cursory', 'curvaceous', 'cushion', 'cussed', 'custodian',
         'custody', 'cuticle', 'cuttlefish', 'cyclone', 'cygnet', 'cynical', 'cynicism', 'cynosure', 'cypress',
         'cytology', 'dabble', 'daguerreotype', 'dainty', 'dalliance', 'dampen', 'dandified', 'dangle', 'dapper',
         'dappled', 'daredevil', 'daubster', 'dauntless', 'dawdle', 'deadlock', 'debacle', 'debase', 'debauch',
         'debauchery', 'debilitate', 'debility', 'debonair', 'debouch', 'debrief', 'debris', 'debunk', 'debutante',
         'decadence', 'decadent', 'decamp', 'deceit', 'decelerate', 'decibel', 'deciduous', 'decimate', 'decipher',
         'declaim', 'declamation', 'declassify', 'declination', 'declivity', 'decode', 'decompose', 'decomposition',
         'decorous', 'decorum', 'decree', 'decrepit', 'decrepitude', 'defamatory', 'defame', 'default', 'defect',
         'defection', 'defendant', 'deference', 'deficiency', 'deficit', 'defile', 'definition', 'deflated', 'deflect',
         'deflection', 'defunct', 'degenerate', 'degrade', 'dehumanize', 'dehydrate', 'deification', 'dejected',
         'dejection', 'delectable', 'delectation', 'delegate', 'delete', 'deleterious', 'deliberate', 'delimit',
         'delineate', 'delinquency', 'delinquent', 'delirious', 'delirium', 'delude', 'deluge', 'delusion', 'demarcate',
         'demean', 'demeanor', 'demesne', 'demobilize', 'demography', 'demolish', 'demolition', 'demote', 'demure',
         'denigrate', 'denizen', 'denominate', 'denomination', 'denouement', 'denounce', 'denture', 'denude', 'deplete',
         'depletion', 'deportment', 'depose', 'deposition', 'depravity', 'depreciate', 'depredation', 'deprivation',
         'depute', 'deputy', 'derangement', 'derelict', 'deride', 'derisive', 'derivative', 'dermatology', 'derogate',
         'derogatory', 'desalinize', 'descant', 'descend', 'descendant', 'descry', 'desecrate', 'desiccant',
         'desiccate', 'desideratum', 'designation', 'desirable', 'desirous', 'desist', 'desolate', 'despicable',
         'despoil', 'despondent', 'despotic', 'despotism', 'destitute', 'destruction', 'desuetude', 'desultory',
         'detached', 'detachment', 'detain', 'detection', 'detente', 'detergent', 'deteriorate', 'deterrent', 'detest',
         'detonate', 'detonation', 'detour', 'detoxicate', 'detractor', 'detriment', 'detrimental', 'detritus',
         'devastate', 'devastating', 'deviant', 'deviate', 'devious', 'devoid', 'devolution', 'devotion', 'devour',
         'dexterity', 'dexterous', 'diabetes', 'diabolical', 'diaphanous', 'diarrhoea', 'diatribe', 'dichotomy',
         'dictate', 'dictator', 'dictum', 'didactic', 'didactics', 'dietetics', 'dietician', 'diffuse', 'diffusion',
         'digress', 'digression', 'dilapidated', 'dilapidation', 'dilate', 'dilatory', 'dilemma', 'dilettante',
         'dilute', 'dilution', 'diminuendo', 'diminutive', 'dimple', 'dinghy', 'diplomatic', 'dipsomania', 'direful',
         'disabuse', 'disaffected', 'disaffection', 'disagreeable', 'disarray', 'disaster', 'disastrous', 'disband',
         'disbar', 'disbarment', 'disburse', 'disbursement', 'discern', 'discernment', 'discharge', 'disciple',
         'disciplinarian', 'disclaim', 'discography', 'discomfit', 'discomfiture', 'discommode', 'discompose',
         'discomposure', 'discontented', 'discordant', 'discourse', 'discourteous', 'discredit', 'discreet',
         'discrepancy', 'discrete', 'discretion', 'discriminating', 'discriminatory', 'discursive', 'disdain',
         'disdainful', 'disembodied', 'disencumber', 'disengaged', 'disfranchise', 'disgorge', 'disgruntled',
         'disguise', 'disinclined', 'disinfectant', 'disingenuous', 'disintegrate', 'disinter', 'disinterested',
         'disjointed', 'dislocate', 'dislocation', 'dislodge', 'disparage', 'disparate', 'disparity', 'dispassionate',
         'dispatch', 'dispel', 'dispensable', 'disport', 'disposed', 'disposition', 'dispossessed', 'disputant',
         'disputatious', 'disquiet', 'disquisition', 'disreputable', 'dissemble', 'disseminate', 'dissent', 'dissenter',
         'dissident', 'dissimulate', 'dissipate', 'dissipated', 'dissolute', 'dissonance', 'dissonant', 'dissuade',
         'distend', 'distension', 'distillation', 'distinction', 'distinguished', 'distracted', 'distraught',
         'distress', 'distressing', 'disturbance', 'dither', 'diurnal', 'divagate', 'diverge', 'divergence', 'diverse',
         'diversity', 'divest (of)', 'divestiture', 'dividend', 'divulge', 'doctrinaire', 'doddle', 'doggerel',
         'dogmatic', 'doldrums', 'doleful', 'doltish', 'domain', 'domesticate', 'domesticity', 'dormant', 'dorsal',
         'dossier', 'dotage', 'doting', 'double-cross', 'downcast', 'downplay', 'downtrodden', 'drabness', 'draconian',
         'drainage', 'drawbridge', 'dreary', 'dredge', 'dredger', 'drenched', 'dribble', 'drizzle', 'drizzly',
         'drollery', 'drudge', 'ductile', 'dulcet', 'duplicity', 'duration', 'duress', 'dwindle', 'dynamic', 'dynamite',
         'dynamo', 'dyslexia', 'dyspepsia', 'earring', 'eavesdrop', 'ebullience', 'ebullient', 'eccentric',
         'eccentricity', 'ecdysis', 'echelon', 'eclectic', 'eclecticism', 'eclipse', 'eclogue', 'economize', 'ecstasy',
         'ecstatic', 'edification', 'edifice', 'efface', 'effeminate', 'effervesce', 'effete', 'effigy', 'effortless',
         'effrontery', 'effulgence', 'effulgent', 'effusive', 'egalitarian', 'egocentric', 'egregious', 'egress',
         'ejaculate', 'ejaculation', 'elaborate', 'elaboration', 'elapse', 'elastic', 'elasticity', 'elated', 'elation',
         'electorate', 'elephantine', 'elicit', 'eligible', 'eliminate', 'elitism', 'elixir', 'ellipse', 'ellipsis',
         'elocution', 'elongate', 'elongation', 'eloquence', 'eloquent', 'elucidate', 'elusive', 'emaciate',
         'emaciated', 'emancipate', 'emancipation', 'embankment', 'embargo', 'embellish', 'embezzle', 'embezzlement',
         'embitter', 'emblem', 'emblematic', 'embodiment', 'embody', 'embolden', 'emboss', 'embroider', 'embroidery',
         'embroil', 'embryo', 'embryonic', 'emendation', 'emerald', 'emerge', 'emergence', 'emergency', 'emetic',
         'emigrate', 'eminence', 'eminent', 'emissary', 'emission', 'emollient', 'emolument', 'empathy', 'empirical',
         'empiricism', 'employ', 'empyreal', 'empyrean', 'emulate', 'emulation', 'emulsify', 'enactment', 'enamoured',
         'encapsulate', 'encephalitis', 'enchant', 'enchanting', 'enchantment', 'encipher', 'enclosure', 'encomium',
         'encompass', 'encroach', 'encroachment', 'encumber', 'encumbrance', 'encyclopedic', 'endearment', 'endemic',
         'endorsement', 'endue (with)', 'enervate', 'enfranchise', 'engaging', 'engender', 'engross', 'engrossing',
         'engulf', 'enhancement', 'enigma', 'enigmatic', 'enjoin', 'enkindle', 'enlightened', 'enlightenment', 'enlist',
         'enlistment', 'enmesh', 'enmity', 'enormity', 'enormous', 'enrapture', 'ensconce', 'ensemble', 'enshrine',
         'ensign', 'ensnare', 'entangle', 'entanglement', 'enterprising', 'enthrall', 'entice', 'enticement', 'entitle',
         'entity', 'entomology', 'entreat', 'entreaty', 'entrench', 'entrenched', 'entrepreneur', 'entrust', 'entwine',
         'enumerate', 'enunciate', 'enunciation', 'environs', 'envisage', 'enzyme', 'epaulet', 'ephemeral', 'epicure',
         'epicurean', 'epidemic', 'epidermis', 'epigram', 'epigrammatic', 'epilogue', 'epistemology', 'epistle',
         'epitaph', 'epithet', 'epitome', 'equable', 'equanimity', 'equilibrium', 'equine', 'equitable', 'equitation',
         'equity', 'equivalence', 'equivalent', 'equivocal', 'equivocate', 'eradicate', 'erasure', 'erosion', 'erotic',
         'errand', 'errant', 'erratic', 'ersatz', 'erudite', 'erudition', 'eruption', 'escalate', 'eschew', 'escort',
         'esoteric', 'espionage', 'espousal', 'espouse', 'establishment', 'estate', 'estimable', 'estrange',
         'estrangement', 'estuary', 'etching', 'ethereal', 'ethnography', 'etiquette', 'etymology', 'eucalyptus',
         'eugenic', 'eulogistic', 'eulogy', 'euphemism', 'euphonious', 'euphony', 'euphoria', 'eurhythmic', 'evacuate',
         'evanescent', 'evasive', 'even-tempered', 'evince', 'eviscerate', 'evocative', 'exacerbate', 'exacting',
         'exaction', 'exaggerate', 'exaggeration', 'exaltation', 'exasperate', 'exasperation', 'excavate', 'excavation',
         'exceed', 'exceedingly', 'exception', 'exceptionable', 'exceptional', 'excesses', 'exchequer', 'excise',
         'excision', 'exclude', 'exclusion', 'exclusive', 'excogitate', 'excoriate', 'excruciating', 'exculpate',
         'excursion', 'execrable', 'execrate', 'executioner', 'executive', 'executor', 'exegesis', 'exempt',
         'exemption', 'exhale', 'exhaustion', 'exhaustive', 'exhibitionism', 'exhibitionist', 'exhilarate',
         'exhilarating', 'exhort', 'exhortation', 'exhume', 'exiguous', 'exodus', 'exogamy', 'exonerate', 'exorbitant',
         'exorcism', 'exorcize', 'exotic', 'expand', 'expansion', 'expatriate', 'expediency', 'expedite', 'expedition',
         'expeditious', 'expend', 'expendable', 'expenditure', 'expertise', 'expiate', 'expiration', 'expire',
         'explicable', 'explicate', 'explicit', 'exploit', 'exploration', 'explore', 'exponent', 'exposition',
         'expostulate', 'expound', 'expressly', 'expropriate', 'expulsion', 'expunge', 'expurgate', 'exquisite',
         'extant', 'extemporize', 'extenuate', 'exterminate', 'extinct', 'extinction', 'extirpate', 'extort',
         'extortion', 'extradite', 'extraneous', 'extrapolate', 'extravagant', 'extremity', 'extricate', 'extrinsic',
         'extrovert', 'exuberant', 'exultant', 'fabric', 'fabricate', 'fabulous', 'facade', 'facetious', 'facile',
         'facilitate', 'facilities', 'facsimile', 'faction', 'factious', 'factitious', 'factotum', 'faddish',
         'fairyland', 'falcon', 'fallacious', 'fallacy', 'fallible', 'fallow', 'falsification', 'falsify',
         'familiarity', 'famish', 'famished', 'fanatic', 'fanaticism', 'fanfare', 'fantasia', 'fantastic',
         'far-reaching', 'farrow', 'fascia', 'fascinate', 'fascinating', 'fascination', 'fastidious', 'fastness',
         'fatality', 'fathom', 'fathomless', 'fatigue', 'fatuity', 'fatuous', 'faucet', 'fawning', 'fealty', 'feasible',
         'febrile', 'feckless', 'fecund', 'feedback', 'feigned', 'felicitate', 'felicitous', 'felicity', 'feline',
         'felony', 'feminist', 'fencer', 'fencing', 'fender', 'ferment', 'fermentation', 'ferocious', 'ferocity',
         'ferret', 'ferrous', 'fertile', 'fertility', 'fervent', 'fervor', 'festal', 'festive', 'fetish', 'fetter',
         'fettered', 'fiasco', 'fickle', 'fictitious', 'fidelity', 'fidget', 'fidgety', 'fiendish', 'fierce', 'figment',
         'figurative', 'figurehead', 'figurine', 'filament', 'filial', 'filial piety', 'filibuster', 'filigree',
         'fillet', 'fillings', 'filthy', 'finable', 'finale', 'finesse', 'finicky', 'firefly', 'firmament', 'fiscal',
         'fishery', 'fissile', 'fissure', 'fitful', 'flabbergast', 'flabby', 'flaccid', 'flagellate', 'flagrant',
         'flamboyance', 'flamboyant', 'flammable', 'flange', 'flaring', 'flatcar', 'flatulence', 'flaunt', 'flavouring',
         'flawless', 'fledged', 'fledgling', 'fleece', 'fleeting', 'flexible', 'flicker', 'flighty', 'flimsy', 'flinch',
         'flinty', 'flippancy', 'flippant', 'flirtatious', 'floppy', 'florid', 'flounder', 'fluctuate', 'fluffy',
         'flummery', 'flummox', 'fluorescent', 'fluster', 'fodder', 'foetus', 'foible', 'foliage', 'folklore', 'foment',
         'fomentation', 'fondle', 'foodstuff', 'foolhardy', 'foolproof', "fool's errand", 'foothold', 'footle',
         'footloose', 'foppish', 'forage', 'forager', 'forbearance', 'forbearing', 'forbidding', 'forceps', 'forebode',
         'foreboding', 'foreclose', 'forensic', 'foreordain', 'forerunner', 'forestall', 'forfeit', 'forfeiture',
         'forger', 'forgery', 'forlorn', 'format', 'formative', 'formidable', 'formulate', 'fornicate', 'forsake',
         'forswear', 'fortitude', 'fortress', 'fortuitous', 'forwardness', 'founder', 'four-poster', 'fracas',
         'fraction', 'fractional', 'fractious', 'fracture', 'fragile', 'fragmentary', 'frailty', 'frame-up', 'frantic',
         'fraternal', 'fraternity', 'fraudulent', 'fraught', 'freckle', 'freeway', 'frenetic', 'fresco', 'fretful',
         'fretwork', 'friable', 'frieze', 'frigate', 'frigidity', 'fringe', 'frisky', 'frivolity', 'frivolous',
         'frolic', 'frolicsome', 'frowzy', 'fructify', 'frugality', 'frustrate', 'fugitive', 'fulcrum', 'full-bodied',
         'full-fledged', 'fulminate', 'fulmination', 'fulsome', 'fulsomeness', 'fumble', 'fumigate', 'functionary',
         'furbish', 'furlough', 'furrow', 'furtive', 'fusillade', 'fustian', 'futility', 'gabble', 'gadfly', 'gadget',
         'gaggle', 'gaiety', 'gainsay', 'galactic', 'galaxy', 'gallant', 'gallantry', 'galley', 'gallop', 'gallows',
         'galvanize', 'gambol', 'gander', 'gangling', 'gangway', 'garble', 'gardenia', 'gargantuan', 'gargoyle',
         'garish', 'garland', 'garment', 'garner', 'garnish', 'garret', 'garrulity', 'garrulous', 'gastric',
         'gastritis', 'gastronomy', 'gauche', 'gaucherie', 'gazetteer', 'generate', 'generator', 'generic',
         'generosity', 'genesis', 'genetic', 'genetics', 'genial', 'geniality', 'genuflect', 'germane', 'germinate',
         'gerontology', 'gestation', 'gesticulate', 'geyser', 'gilded', 'gimmick', 'ginger', 'girder', 'girdle',
         'gladiator', 'glamorous', 'glamour', 'glaring', 'gleaner', 'gleanings', 'gleeful', 'glider', 'glimmer',
         'glimpse', 'glisten', 'gloaming', 'gloomy', 'glossary', 'glossy', 'glower', 'glucose', 'glutinous', 'glutton',
         'gluttony', 'gnarled', 'gnawing', 'gneiss', 'gnomic', 'gobble', 'goblet', 'gorgeous', 'gorgon', 'gormandize',
         'gosling', 'gospel', 'gossamer', 'gourmand', 'gourmet', 'governance', 'gradient', 'granary', 'grandeur',
         'grandiloquent', 'grandiose', 'grandstand', 'granite', 'granular', 'granulate', 'granule', 'graphic',
         'grasping', 'grateful', 'gratification', 'gratify', 'grating', 'gratis', 'gratuitous', 'gratuity', 'gravel',
         'gravity', 'greenhorn', 'greenhouse', 'gregarious', 'gridiron', 'grievance', 'grievous', 'grille', 'grimace',
         'grindstone', 'gripping', 'grisly', 'gristle', 'groggy', 'groove', 'gropingly', 'grotesque', 'grouch',
         'grouse', 'grovel', 'groveler', 'grudge', 'grudging', 'gruelling', 'gruesome', 'grumble', 'grumpy', 'guarded',
         'guffaw', 'guillotine', 'gullible', 'gumption', 'gusher', 'gustation', 'gutless', 'gutter', 'guttle',
         'guttural', 'guzzle', 'gynaecocracy', 'gyrate', 'gyroscope', 'habitat', 'habituate', 'hackneyed',
         'haemophilia', 'haemorrhage', 'haemostat', 'haggard', 'haggle', 'halcyon', 'hallow', 'hallowed', 'halting',
         'hamper', 'handle', 'hangar', 'hanger', 'hangover', 'hapless', 'harangue', 'harass', 'harassment', 'harbinger',
         'harbor', 'hard-bitten', 'hardheaded', 'hardihood', 'hard-nosed', 'harmonize', 'harness', 'harpoon',
         'harpsichord', 'harridan', 'harrow', 'harrowing', 'hassle', 'hasten', 'hatchet', 'haughtiness', 'haughty',
         'haunting', 'hauteur', 'haversack', 'hawker', 'hawser', 'hazard', 'hazardous', 'heading', 'hearsay', 'heathen',
         'heavy-handed', 'hecatomb', 'heckle', 'heckler', 'hectic', 'hector', 'hedgehog', 'hedonism', 'hedonistic',
         'hegemony', 'heinous', 'heiress', 'heliotrope', 'helmet', 'helmsman', 'helping', 'henpecked', 'hepatic',
         'hepatitis', 'herald', 'herbaceous', 'herbivorous', 'herdsman', 'heresy', 'heretic', 'heretical', 'heritage',
         'hermetic', 'hermit', 'hermitage', 'heroics', 'heterodox', 'heterodoxy', 'heterogeneous', 'hexagon', 'heyday',
         'hiatus', 'hibernate', 'hibernation', 'hibiscus', 'hidebound', 'hideous', 'hierarchy', 'hieroglyph',
         'highbrow', 'high-flown', 'hilarious', 'hilarity', 'hillbilly', 'hinder', 'hindrance', 'hinterland',
         'hippopotamus', 'hipster', 'hirsute', 'histology', 'histrionic', 'histrionics', 'hoarse', 'hobble',
         'hobgoblin', 'hollow', 'holocaust', 'holograph', 'holster', 'homage', 'homely', 'homeopathy', 'homiletics',
         'homogeneous', 'homogenize', 'homograph', 'honorarium', 'honours', 'hoodwink', 'hooked', 'hooligan', 'horizon',
         'hormone', 'horology', 'horrendous', 'horror', "hors d'oeuvre", 'hortative', 'horticulture', 'hosepipe',
         'hospitality', 'hostage', 'hostile', 'hostility', 'hot water', 'hotbed', 'howler', 'hoyden', 'hubbub',
         'hubris', 'huckster', 'hucksterize', 'huddle', 'hulking', 'hullabaloo', 'humane', 'humanity', 'humble',
         'humdinger', 'humdrum', 'humidity', 'humiliate', 'humility', 'hummingbird', 'hummock', 'humour', 'hurdle',
         'hurly-burly', 'hurricane', 'husbandry', 'hustings', 'hustler', 'hybrid', 'hydrant', 'hydrate', 'hygiene',
         'hygroscopic', 'hyperbole', 'hyperbolic', 'hypercritical', 'hypersensitive', 'hyphen', 'hypnosis', 'hypnotic',
         'hypochondria', 'hypochondriac', 'hypocrisy', 'hypodermic', 'hypotenuse', 'hypothesis', 'hypothetical',
         'hysteria', 'hysterical', 'icicle', 'iconoclast', 'identification', 'identify', 'ideology', 'idiocy',
         'idiosyncrasy', 'idolater', 'idolatrous', 'igneous', 'ignite', 'ignoble', 'ignominious', 'ignominy',
         'ignoramus', 'ignorance', 'iguana', 'illegality', 'illegible', 'illegitimate', 'illiberal', 'illicit',
         'illiterate', 'illuminating', 'illumination', 'illusory', 'illustration', 'illustrious', 'imaginary',
         'imbecile', 'imbecility', 'imbibe', 'imbroglio', 'imbue with', 'immaculate', 'immanent', 'immaterial',
         'immediacy', 'immemorial', 'immense', 'immensity', 'immerse', 'immersion', 'imminence', 'imminent',
         'immoderate', 'immolate', 'immolation', 'immoral', 'immortal', 'immune', 'immunity', 'immunize', 'immure',
         'immutable', 'impair', 'impale', 'impalpable', 'impart', 'impartial', 'impasse', 'impassioned', 'impassive',
         'impeach', 'impeccable', 'impecunious', 'impede', 'impediment', 'impedimenta', 'impending', 'impenetrable',
         'impenitent', 'imperative', 'imperceptible', 'imperil', 'imperious', 'impermeable', 'impersonate',
         'impertinent', 'imperturbable', 'impervious', 'impetuous', 'impetus', 'implacable', 'implant', 'implement',
         'implicate', 'implication', 'implicit', 'implode', 'implore', 'implosion', 'impolitic', 'imponderable',
         'importunate', 'importune', 'impose', 'imposing', 'impostor', 'imposture', 'impotent', 'impound', 'impoverish',
         'imprecation', 'impregnable', 'impregnate', 'impresario', 'impressionable', 'imprint', 'impromptu',
         'impropriety', 'improvident', 'improvisation', 'improvise', 'impudent', 'impugn', 'impulse', 'impulsive',
         'impunity', 'imputation', 'impute to', 'inadvertent', 'inalienable', 'inanimate', 'inanition', 'inanity',
         'inaugurate', 'inborn', 'inbound', 'incandescent', 'incapacity', 'incarcerate', 'incarnate', 'incarnation',
         'incendiary', 'incense', 'incentive', 'inception', 'incertitude', 'incessant', 'inchoate', 'incinerate',
         'incipience', 'incipient', 'incise', 'incision', 'incisive', 'incisor', 'incite', 'incivility', 'inclement',
         'inclination', 'incline', 'inclined', 'incognito', 'incoherent', 'incommensurate', 'incommodious',
         'incommunicado', 'incommunicative', 'incompatible', 'incompetent', 'inconceivable', 'incongruity',
         'incongruous', 'inconsequential', 'inconsiderate', 'inconsolable', 'inconstant', 'incontestable',
         'incontinent', 'incorporate', 'incorporeal', 'incorrigible', 'increment', 'incriminate', 'incrustation',
         'incubation', 'incubator', 'incubus', 'inculcate', 'incumbency', 'incumbent', 'incurable', 'incursion',
         'indebted', 'indefatigable', 'indefinite', 'indelible', 'indemnification', 'indemnify', 'indent',
         'indentation', 'indented', 'indenture', 'indescribable', 'indict', 'indifferent', 'indigenous', 'indigent',
         'indignant', 'indignation', 'indiscernible', 'indiscreet', 'indiscretion', 'indiscriminate', 'indispensable',
         'indisposed', 'indivisible', 'indocile', 'indoctrinate', 'indolent', 'indomitable', 'indubitable', 'induce',
         'inducement', 'induct', 'induction', 'inebriate', 'ineffable', 'ineffaceable', 'ineligible', 'ineluctable',
         'ineptitude', 'inertia', 'inexhaustible', 'inexorable', 'inexpedient', 'inexpiable', 'inexplicable',
         'inextricable', 'infallibility', 'infallible', 'infamous', 'infamy', 'infantile', 'infantry', 'infatuated',
         'infatuation', 'infelicitous', 'infernal', 'inferno', 'infest', 'infidel', 'infidelity', 'infiltrate',
         'infinitesimal', 'infinity', 'infirmity', 'inflame', 'inflamed', 'inflammable', 'inflated', 'inflation',
         'infliction', 'informer', 'infraction', 'infringe', 'infringement', 'infuriate', 'infuse', 'infusion',
         'ingenious', 'ingenuity', 'ingenuous', 'ingest', 'ingrained', 'ingrate', 'ingratiate', 'ingratiating',
         'ingratitude', 'ingredient', 'ingress', 'inhale', 'inherent', 'inhibited', 'inhuman', 'inhumane', 'inimical',
         'inimitable', 'iniquitous', 'iniquity', 'initiative', 'injunction', 'inkling', 'innate', 'innocuous',
         'innuendo', 'inoculate', 'inoculation', 'inordinate', 'inquietude', 'inquisitive', 'inroad', 'insane',
         'insanity', 'inscription', 'inscrutable', 'insert', 'insertion', 'insider', 'insidious', 'insignia',
         'insinuate', 'insipid', 'insistence', 'insolate', 'insolent', 'insolvent', 'insomnia', 'insouciance',
         'inspection', 'inspiration', 'inspired', 'installation', 'installment', 'instantaneous', 'instigate',
         'instigation', 'instill', 'institute', 'instrumental', 'insubordinate', 'insufferable', 'insufficiency',
         'insufficient', 'insular', 'insularity', 'insulate', 'insulin', 'insuperable', 'insurgent', 'insurrection',
         'intact', 'intaglio', 'intangible', 'integrate', 'integrated', 'integrity', 'integument', 'intelligible',
         'intemperate', 'interaction', 'intercede', 'intercept', 'interchangeable', 'interdict', 'interim', 'interlace',
         'interlock', 'interlocutor', 'interlude', 'intermediary', 'interminable', 'intermingle', 'intermission',
         'intermittent', 'intern', 'internecine', 'internment', 'interplay', 'interpolate', 'interpolation',
         'interpose', 'interposition', 'interregnum', 'interrelate', 'interrogate', 'interrogative', 'intersect',
         'intersection', 'intersperse', 'interstice', 'intertwine', 'intervene', 'intervention', 'interweave',
         'intestate', 'intestinal', 'intestine', 'intimacy', 'intimate', 'intimidate', 'intimidation', 'intolerant',
         'intoxicant', 'intoxicate', 'intractable', 'intransigence', 'intransigent', 'intrepid', 'intrepidity',
         'intricacy', 'intricate', 'intrigue', 'intriguing', 'intrinsic', 'introspection', 'introspective', 'introvert',
         'intrude', 'intrusion', 'intuitive', 'intumescence', 'inundate', 'inundation', 'inured', 'invalid',
         'invalidate', 'invective', 'inveigle', 'inventory', 'inverse', 'invert', 'invertebrate', 'investiture',
         'inveterate', 'invidious', 'invigilate', 'invigorate', 'invincible', 'inviolable', 'inviolate', 'inviting',
         'invocation', 'invoice', 'invoke', 'involved', 'invulnerable', 'iodine', 'irascible', 'iridescent', 'irksome',
         'ironclad', 'ironic', 'irradiate', 'irreconcilable', 'irreparable', 'irreproachable', 'irresistible',
         'irreverent', 'irrevocable', 'irrigate', 'irritable', 'irritate', 'isthmus', 'iterate', 'itinerant',
         'itinerary', 'jabber', 'jagged', 'jaguar', 'jamboree', 'janitor', 'jargon', 'jaundiced', 'jaunty', 'jejune',
         'jeopardize', 'jeopardy', 'jeremiad', 'jesting', 'jesuitical', 'jettison', 'jigsaw puzzle', 'jingoism',
         'jocose', 'jocund', 'jollity', 'jubilant', 'jubilation', 'judicial', 'judicious', 'juggernaut', 'jumble',
         'jurisprudence', 'justifiable', 'juvenile', 'juxtapose', 'juxtaposition', 'kaleidoscopic', 'kangaroo',
         'karate', 'kennel', 'kerfuffle', 'kernel', 'kindle', 'kinetic', 'kitsch', 'kitten', 'kleptomania', 'knackered',
         'knocker', 'knotty', 'knowledgeable', 'labile', 'laborious', 'labour', 'laboured', 'labyrinth', 'lacerate',
         'laceration', 'lacework', 'lachrymose', 'lackadaisical', 'lackey', 'lacklustre', 'laconic', 'lactic',
         'laggard', 'lambaste', 'lament', 'lamentable', 'laminate', 'lampoon', 'lampooner', 'lancinate', 'landlocked',
         'landslide', 'languid', 'languish', 'languor', 'lapidary', 'larceny', 'largesse', 'laryngitis', 'larynx',
         'lascivious', 'lassitude', 'latency', 'latent', 'latitude', 'lattice', 'laudable', 'laudatory', 'laurel',
         'laurels', 'laxative', 'laxity', 'layabout', 'layman', 'leaflet', 'leakage', 'leaven', 'lecherous', 'lechery',
         'ledger', 'leeward', 'legacy', 'legend', 'legerdemain', 'legible', 'legion', 'legislate', 'legislature',
         'legitimate', 'lengthy', 'lenience', 'lenient', 'leonine', 'leprosy', 'lesion', 'lessee', 'lethal', 'lethargy',
         'leucocyte', 'leviathan', 'levitate', 'levity', 'lexical', 'lexicographer', 'lexicon', 'liability', 'liable',
         'liaison', 'libation', 'libellous', 'liberality', 'liberated', 'libertine', 'libidinous', 'libido', 'libretto',
         'licence', 'licentious', 'ligature', 'ligneous', 'lilliputian', 'limber', 'limerick', 'limnetic', 'limousine',
         'limpid', 'lineal', 'linear', 'linger', 'lingering', 'lingual', 'linguistics', 'linoleum', 'lionize',
         'liquefy', 'liquidate', 'liquidation', 'liquor', 'lissom', 'listless', 'literal', 'literati', 'litigant',
         'litigious', 'litter', 'litterbin', 'littoral', 'liturgical', 'liturgy', 'livable', 'lively', 'liverish',
         'loathe', 'loathsome', 'lobster', 'locale', 'locomotion', 'locomotive', 'locust', 'locution', 'lodger',
         'logistics', 'logjam', 'loiter', 'longevity', 'longitude', 'longueur', 'loquacious', 'lottery', 'lounge',
         'lounger', 'loutish', 'lowbred', 'lubricant', 'lubricious', 'lucrative', 'lucubrate', 'lucubration',
         'lugubrious', 'lukewarm', 'lullaby', 'lumber', 'luminary', 'luminous', 'lumpish', 'lunacy', 'lunatic',
         'luscious', 'lustre', 'lustrous', 'luxuriant', 'macabre', 'macadam', 'macerate', 'machination', 'mackintosh',
         'macrocosm', 'maddening', 'madrigal', 'maelstrom', 'maestro', 'magenta', 'magisterial', 'magistracy',
         'magistrate', 'magnanimous', 'magnate', 'magnetism', 'magnification', 'magnify', 'magniloquent', 'magnitude',
         'magpie', 'maisonette', 'makeshift', 'maladroit', 'malapropism', 'malcontent', 'malcontented', 'malediction',
         'malevolent', 'malfunction', 'malice', 'malicious', 'malign', 'malignant', 'malignity', 'malinger',
         'malleable', 'mallet', 'malnutrition', 'malodorous', 'maltreat', 'mammal', 'manacle', 'mandate', 'mandatory',
         'maneuvrable', 'maneuvre', 'mangle', 'maniacal', 'manifest', 'manifesto', 'manifold', 'manikin',
         'manipulative', 'mannequin', 'mansion', 'mantle', 'manumit', 'manuscript', 'maraud', 'margarine', 'marginal',
         'marine', 'mariner', 'marionette', 'marital', 'maroon', 'marquetry', 'marrow', 'marsupial', 'martinet',
         'martyr', 'masonry', 'masquerade', 'massacre', 'massive', 'masticate', 'matador', 'materialize', 'matriarchy',
         'matrix', 'mattress', 'maturity', 'maudlin', 'maverick', 'mawkish', 'mayhem', 'meadow', 'meager', 'meander',
         'measles', 'measured', 'meddlesome', 'median', 'mediate', 'medieval', 'mediocre', 'mediocrity', 'meditative',
         'medium', 'medley', 'megalith', 'megalomania', 'melancholy', 'mellifluous', 'melodious', 'melodrama', 'melody',
         'membrane', 'memento', 'memorial', 'menace', 'menagerie', 'mendacious', 'mendacity', 'mendicant', 'menial',
         'mentor', 'mercenary', 'merchandise', 'mercurial', 'meretricious', 'meritorious', 'mermaid', 'mesmerize',
         'metabolism', 'metamorphosis', 'metaphor', 'metaphorical', 'metaphysics', 'meteoric', 'meticulous', 'mettle',
         'mettlesome', 'miasma', 'microbe', 'microscopic', 'midget', 'migrant', 'mildew', 'milieu', 'militant',
         'miller', 'millinery', 'mimicry', 'minaret', 'minatory', 'miniature', 'minion', 'minnow', 'minuet', 'minutia',
         'mirage', 'misanthrope', 'miscellaneous', 'miscellany', 'mischievous', 'misconstrue', 'miscreant', 'mishap',
         'missile', 'mistimed', 'mistral', 'mitigate', 'mitten', 'mnemonics', 'moderate', 'moderator', 'modicum',
         'modification', 'modify', 'modish', 'modulate', 'moiety', 'molest', 'mollify', 'mollusk', 'mollycoddle',
         'momentary', 'momentous', 'momentum', 'monarch', 'monastery', 'monasticism', 'mongrel', 'monogamy',
         'monograph', 'monolithic', 'monologue', 'monopoly', 'monotonous', 'monsoon', 'monster', 'monstrous', 'moppet',
         'morale', 'moralist', 'moralistic', 'morass', 'moratorium', 'morbid', 'morbidity', 'mordant', 'moribund',
         'morose', 'morphemics', 'morsel', 'mortar', 'mortgage', 'mortification', 'mortify', 'mortise', 'mortuary',
         'mosaic', 'motivate', 'motivation', 'motley', 'mottled', 'moulder', 'mountebank', 'mournful', 'movement',
         'muckrake', 'muddle', 'muffle', 'muffler', 'multifarious', 'multitude', 'mundane', 'munificent', 'muniments',
         'munitions', 'murmur', 'muster', 'mutation', 'mutilate', 'mutineer', 'mutinous', 'mutton', 'mycology',
         'myopia', 'myriad', 'mythology', 'naivety', 'narcissism', 'narcotic', 'nascent', 'nativity', 'nausea',
         'nauseate', 'nautical', 'nebula', 'nebulous', 'necessitous', 'necromancy', 'necropolis', 'needle', 'nefarious',
         'negate', 'negation', 'negligence', 'negligible', 'negotiable', 'nemesis', 'neolithic', 'neologism', 'neonate',
         'neophyte', 'nephritis', 'nepotism', 'nerveless', 'nestling', 'nether', 'nethermost', 'nettle', 'neurology',
         'neurosis', 'neurotic', 'neutral', 'neutralize', 'nibble', 'nicotine', 'niggard', 'niggardly', 'niggle',
         'niggling', 'nightmare', 'nihilism', 'nimble', 'nippers', 'nipping', 'nirvana', 'nitpick', 'nocturnal',
         'noggin', 'noisome', 'nomadic', 'nomenclature', 'nominal', 'nomination', 'nonchalance', 'nonchalant',
         'noncommittal', 'nonconformist', 'nonconformity', 'nondescript', 'nonentity', 'nonesuch', 'nonflammable',
         'nonobservance', 'nonpareil', 'nonplus', 'nonskid', 'nonviolent', 'normative', 'nosedive', 'nosegay',
         'nostalgia', 'nostrum', 'notability', 'notched', 'notify', 'notoriety', 'notorious', 'novelettish', 'novelty',
         'novice', 'novocaine', 'noxious', 'nuance', 'nubile', 'nudity', 'nugatory', 'nullify', 'nullity', 'numerology',
         'numinous', 'numismatic', 'numismatist', 'nunnery', 'nuptial', 'nuptials', 'nuzzle', 'oafish', 'obbligato',
         'obdurate', 'obedient', 'obeisance', 'obesity', 'obfuscate', 'objection', 'objectionable', 'oblation',
         'obligation', 'obligatory', 'obliging', 'oblique', 'obliterate', 'oblivion', 'oblivious', 'obloquy',
         'obnoxious', 'obscene', 'obscure', 'obscurity', 'obsequies', 'obsequious', 'observance', 'obsession',
         'obsolescent', 'obsolete', 'obstacle', 'obstetrics', 'obstinate', 'obstreperous', 'obstruct', 'obstruction',
         'obtrude', 'obtrusive', 'obtuse', 'obverse', 'obviate', 'occidental', 'occult', 'occurrence', 'octogenarian',
         'ocular', 'oculist', 'oddments', 'odious', 'odoriferous', 'oesophagus', 'offense', 'offensive', 'officious',
         'offset', 'ogreish', 'ointment', 'oleaginous', 'olfactory', 'oligarchy', 'ominous', 'omission', 'omnipotent',
         'omniscient', 'omnivorous', 'onerous', 'onlooker', 'onslaught', 'ontology', 'opacity', 'opalescent', 'opaque',
         'operative', 'operetta', 'ophthalmology', 'opiate', 'opinionated', 'opponent', 'opportune', 'oppressive',
         'opprobrious', 'opprobrium', 'optimism', 'optimum', 'optional', 'opulence', 'opulent', 'oracle', 'oracular',
         'oration', 'oratorio', 'oratory', 'orchid', 'ordain', 'ordeal', 'ordinance', 'ordination', 'ordnance',
         'organism', 'orient', 'orientation', 'orifice', 'ornate', 'ornithology', 'orotund', 'orthodontics', 'orthodox',
         'orthodoxy', 'orthopedics', 'oscillate', 'oscillation', 'osculation', 'osmosis', 'osseous', 'ossify',
         'ostensible', 'ostentation', 'ostracize', 'ostrich', 'otherworldly', 'otiose', 'outbid', 'outface', 'outfox',
         'outgoing', 'outlandish', 'outmoded', 'outrage', 'outrageous', 'outset', 'outskirts', 'outstrip', 'outwit',
         'ovation', 'overact', 'overbearing', 'overdose', 'overhaul', 'overlap', 'overreach', 'override', 'overriding',
         'overrule', 'overshadow', 'overture', 'overweening', 'overwhelm', 'overwhelming', 'overwrought', 'oxidize',
         'oyster', 'pabulum', 'pachyderm', 'pacifier', 'packed', 'paganism', 'pageant', 'painkiller', 'palatable',
         'palate', 'palatial', 'palaver', 'paleography', 'paleolithic', 'palette', 'palings', 'palisade', 'palliate',
         'palliation', 'pallid', 'palpable', 'palpitate', 'paltry', 'pamper', 'pamphlet', 'panacea', 'panache',
         'pancreas', 'pandemic', 'pandemonium', 'pander', 'panegyric', 'panoply', 'panorama', 'pantheon', 'pantomime',
         'pantry', 'papoose', 'papyrus', 'parable', 'paradigm', 'paradigmatic', 'paradox', 'paragon', 'paralysis',
         'paralyze', 'paramount', 'paranoia', 'paranoid', 'parasite', 'parasitic', 'parchment', 'parenthesis', 'pariah',
         'parley', 'parlous', 'parochial', 'parody', 'paroxysm', 'parquet', 'parquetry', 'parsimonious', 'partiality',
         'particulars', 'partisan', 'partition', 'parturition', 'parvenu', 'pastel', 'pasteurize', 'pastiche',
         'pastime', 'pastor', 'pastoral', 'pastry', 'patchwork', 'patent', 'pathetic', 'pathology', 'pathos', 'patina',
         'patriarchy', 'patrician', 'patriotism', 'patronage', 'paucity', 'pauper', 'pawnbroker', 'pebble',
         'peccadillo', 'peckish', 'pectoral', 'peculate', 'pecuniary', 'pedagogy', 'pedant', 'pedantry', 'pedestal',
         'pedestrian', 'pediatrics', 'pedigree', 'peevish', 'pejorative', 'pelagic', 'pell-mell', 'pellucid',
         'penalize', 'penalty', 'penance', 'penchant', 'pendent', 'pending', 'pendulous', 'pendulum', 'penetrate',
         'penetrating', 'penetration', 'penitent', 'penitentiary', 'pennant', 'pension', 'pensive', 'penultimate',
         'penumbra', 'penurious', 'penury', 'peppery', 'pepsin', 'peptic', 'perambulate', 'perceive', 'perceptible',
         'perception', 'perceptive', 'percipient', 'percolate', 'percussion', 'percussionist', 'peregrination',
         'peremptory', 'perennial', 'perfectionist', 'perfidious', 'perfidy', 'perforate', 'perfume', 'perfunctory',
         'pergola', 'perigee', 'perilous', 'perimeter', 'period', 'peripatetic', 'peripheral', 'periphery',
         'periphrasis', 'periphrastic', 'perish', 'perishable', 'perishing', 'perjure', 'perjury', 'permeable',
         'permeate', 'permissive', 'permutation', 'pernicious', 'peroration', 'perpendicular', 'perpetrate',
         'perpetuate', 'perpetuity', 'perplexed', 'perplexity', 'perquisite', 'persecute', 'persecution', 'persevere',
         'persevering', 'persiflage', 'persistent', 'persnickety', 'personable', 'personage', 'personalities',
         'personification', 'perspective', 'perspicacious', 'perspiration', 'persuasive', 'pertain', 'pertinacious',
         'pertinent', 'perturbation', 'peruse', 'pervade', 'pervasive', 'perverse', 'perversion', 'perversity',
         'pervert', 'pester', 'pesticide', 'pestilent', 'pestle', 'petition', 'petitioner', 'petrifaction', 'petrify',
         'petrology', 'pettish', 'petulant', 'phantasmal', 'phantom', 'pharisaic', 'pharmaceutical', 'pharmacology',
         'philander', 'philanthropist', 'philatelist', 'philately', 'philistine', 'philology', 'phlegmatic', 'phobia',
         'photosynthesis', 'phrase', 'piazza', 'pierce', 'piercing', 'pigment', 'pigsty', 'pilfer', 'pilgrim',
         'pillage', 'pillory', 'pincers', 'pinion', 'pinnacle', 'piquant', 'piracy', 'pirate', 'pirouette',
         'piscatorial', 'pistol', 'pitcher', 'pitfall', 'pittance', 'placate', 'placebo', 'placid', 'plagiarism',
         'plague', 'plaintiff', 'plaintive', 'plangent', 'plankton', 'plaque', 'plaster', 'plastered', 'plastic',
         'plasticity', 'plateau', 'platitude', 'platonic', 'plausible', 'playwright', 'plebeian', 'plenitude',
         'pleonastic', 'plethora', 'pliable', 'pliant', 'pliers', 'plinth', 'plumage', 'plummet', 'plumule', 'plunder',
         'plutocracy', 'pneumonia', 'podiatry', 'podium', 'poetaster', 'poignancy', 'poignant', 'pointer', 'polarity',
         'polarization', 'polemic', 'polemical', 'polish', 'pollen', 'pollinate', 'pollster', 'poltroon', 'polyandry',
         'polygamy', 'polyglot', 'polymath', 'pomposity', 'pompous', 'poncho', 'ponder', 'ponderous', 'poniard',
         'pontifical', 'populace', 'populous', 'porcelain', 'porcine', 'porcupine', 'porous', 'portable', 'portend',
         'portent', 'portentous', 'portfolio', 'portico', 'poseur', 'positiveness', 'possessed', 'posterior',
         'posterity', 'posthumous', 'postulate', 'potable', 'potation', 'potency', 'potent', 'potentate', 'pother',
         'potpourri', 'pragmatic', 'pragmatism', 'prance', 'prattle', 'preach', 'preamble', 'precarious', 'precede',
         'precedent', 'precept', 'preceptor', 'precinct', 'precipice', 'precipitate', 'precipitation', 'precipitous',
         'precis', 'preclude', 'precocious', 'precognition', 'preconception', 'precursor', 'predator', 'predestine',
         'predicament', 'predictable', 'predilection', 'predisposition', 'predominant', 'preeminent', 'preempt',
         'preemption', 'preface', 'prefigure', 'pregnancy', 'pregnant', 'prejudicial', 'preliterate', 'prelude',
         'premeditated', 'premiere', 'premium', 'preoccupied', 'preponderance', 'preponderate', 'prepossessing',
         'preposterous', 'prerequisite', 'prerogative', 'presage', 'prescient', 'prescribed', 'prescript',
         'prescription', 'presenter', 'preservative', 'preserve', 'preside', 'prestidigitation', 'prestigious',
         'presto', 'presumable', 'presumption', 'presumptuous', 'presupposition', 'pretence', 'pretended', 'pretension',
         'pretentious', 'pretentiousness', 'preternatural', 'pretext', 'prevail', 'prevailing', 'prevalent',
         'prevaricate', 'prevision', 'prickle', 'prickly', 'primate', 'primer', 'primeval', 'primitive', 'primordial',
         'princely', 'priority', 'pristine', 'privation', 'privilege', 'probation', 'probing', 'probity', 'proboscis',
         'proceeds', 'procession', 'proclivity', 'procrastinate', 'procreate', 'procrustean', 'proctor', 'procurement',
         'prodigal', 'prodigious', 'prodigy', 'profane', 'profanity', 'proffer', 'proficient', 'profile', 'profiteer',
         'profligate', 'profundity', 'profuse', 'profusion', 'progenitor', 'progeny', 'prognosticate', 'prohibitive',
         'projectile', 'proletarian', 'proliferate', 'prolific', 'prolix', 'prologue', 'prolong', 'prolonged',
         'promenade', 'promiscuity', 'promiscuous', 'prompt', 'prompting', 'promptness', 'promulgate', 'pronounced',
         'propagate', 'propel', 'propeller', 'propensity', 'prophylactic', 'propinquity', 'propitiate', 'propitiatory',
         'propitious', 'proponent', 'proprietary', 'propriety', 'propulsion', 'prorogation', 'prorogue', 'prosaic',
         'proscribe', 'prosecute', 'prosecutor', 'proselyte', 'proselytize', 'prosody', 'prospective', 'prospectus',
         'prosperity', 'prosperous', 'prostrate', 'protagonist', 'protean', 'protest', 'protocol', 'prototype',
         'protract', 'protrude', 'protrusive', 'protuberance', 'protuberant', 'provenance', 'provender', 'proverbially',
         'providence', 'provident', 'provincial', 'provision', 'provisional', 'provisions', 'provocation',
         'provocative', 'provoke', 'provoking', 'prowess', 'proximate', 'proximity', 'prudence', 'prudery', 'prudish',
         'prurience', 'prurient', 'psephology', 'pseudonym', 'psyche', 'psychedelic', 'psychiatric', 'psychiatry',
         'psychic', 'psychoanalysis', 'psychosis', 'psychotic', 'puberty', 'publicize', 'pucker', 'puddle', 'puerile',
         'puerility', 'pugilism', 'pugnacious', 'pugnacity', 'puissance', 'puissant', 'pulchritude', 'pulchritudinous',
         'pulley', 'pullulate', 'pulmonary', 'pulsate', 'pulsating', 'pulverize', 'pummel', 'punctilious', 'puncture',
         'pundit', 'pungency', 'pungent', 'purblind', 'purchase', 'purebred', 'purgation', 'purgative', 'purgatory',
         'puritanical', 'purlieus', 'purloin', 'purport', 'purvey', 'purveyance', 'pusillanimous', 'putrefaction',
         'putrefy', 'putrid', 'putsch', 'puttee', 'pyromania', 'python', 'quadrangle', 'quagmire', 'quandary',
         'quantum', 'quarantine', 'quarry', 'quartet', 'queasy', 'quench', 'querulous', 'quibble', 'quickie',
         'quiescent', 'quintessence', 'quisling', 'quitter', 'quiver', 'quixotic', 'quizzical', 'quotidian', 'rabble',
         'raconteur', 'radiance', 'radiate', 'radiation', 'raffish', 'rafter', 'ragged', 'raillery', 'raiment',
         'raisin', 'ramble', 'rambunctious', 'ramification', 'ramify', 'rampage', 'rampant', 'rampart', 'rancid',
         'rancor', 'rancorous', 'rankle', 'ransack', 'ransom', 'rapacious', 'rapacity', 'rapids', 'rapine', 'rapport',
         'rapprochement', 'rapture', 'rapturous', 'rashness', 'ratiocination', 'rationale', 'raucous', 'ravenous',
         'ravine', 'ravish', 'ravishing', 'ravishment', 'rawhide', 'razzle', 'reactionary', 'reactivate', 'reagent',
         'reaper', 'reassurance', 'reassure', 'rebarbative', 'rebate', 'rebellious', 'rebuff', 'rebuke', 'rebuttal',
         'recalcitrance', 'recalcitrant', 'recant', 'recantation', 'recapitulate', 'recede', 'receptacle', 'receptive',
         'recess', 'recession', 'recessive', 'recherche', 'recidivism', 'reciprocal', 'reciprocate', 'reciprocity',
         'recital', 'reckless', 'reclaim', 'recluse', 'recoil', 'recompense', 'reconcile', 'reconciliation',
         'recondite', 'reconnaissance', 'recount', 'recoup', 'recreant', 'recreation', 'recriminate', 'recruit',
         'rectification', 'rectify', 'rectitude', 'recumbent', 'recuperate', 'recuperative', 'recurrence', 'recusant',
         'redeem', 'redemption', 'redolent', 'redoubtable', 'redound', 'redress', 'redundancy', 'redundant', 'referee',
         'refinement', 'reflect', 'reflection', 'reflective', 'refractory', 'refrain', 'refulgence', 'refulgent',
         'refurbish', 'refute', 'regale', 'regenerate', 'regent', 'regime', 'regimen', 'regiment', 'regimentation',
         'regressive', 'regulate', 'regulation', 'regurgitate', 'rehabilitate', 'rehash', 'rehearsal', 'reimburse',
         'reimbursement', 'reincarnate', 'reincarnation', 'reinforce', 'reinstate', 'reiterate', 'rejoice', 'rejoicing',
         'rejoin', 'rejoinder', 'rejuvenate', 'rekindle', 'relapse', 'relaxation', 'relegate', 'relent', 'relentless',
         'relevance', 'reliance', 'relict', 'relinquish', 'relish', 'remainder', 'remains', 'remediable', 'reminisce',
         'reminiscence', 'remiss', 'remission', 'remittance', 'remittent', 'remnant', 'remodel', 'remonstrance',
         'remonstrate', 'remorse', 'remunerate', 'remunerative', 'renaissance', 'renascent', 'render', 'rendering',
         'rendezvous', 'renegade', 'renege', 'renounce', 'renown', 'renowned', 'renunciation', 'reparable',
         'reparation', 'repartee', 'repatriate', 'repeal', 'repellent', 'repent', 'repentance', 'repentant',
         'repercussion', 'repertoire', 'repine', 'replacement', 'replenish', 'replete', 'repletion', 'replica',
         'replicate', 'repose', 'repository', 'repossess', 'reprehend', 'reprehensible', 'repress', 'repressive',
         'reprieve', 'reprimand', 'reprisal', 'reproach', 'reprobate', 'reproduction', 'reproof', 'reprove',
         'reptilian', 'repudiate', 'repugnance', 'repugnant', 'repulse', 'repulsive', 'reputable', 'reputation',
         'requiem', 'requisite', 'requisition', 'requital', 'requite', 'rescind', 'rescript', 'resemblance', 'resent',
         'resentment', 'reserve', 'reserved', 'reshuffle', 'residence', 'residual', 'residue', 'resignation',
         'resigned', 'resilience', 'resonance', 'resonant', 'resort', 'resort to', 'respecter', 'respective',
         'respiration', 'respite', 'resplendence', 'resplendent', 'respondent', 'responsive', 'restitution', 'restive',
         'restorative', 'restrain', 'restraint', 'resume', 'resumption', 'resurgence', 'resurgent', 'resurrect',
         'resurrection', 'resuscitate', 'retail', 'retailer', 'retaliate', 'retard', 'retarded', 'retention',
         'retentive', 'reticent', 'reticulation', 'retinue', 'retiring', 'retort', 'retrace', 'retract', 'retreat',
         'retrench', 'retribution', 'retributive', 'retrieval', 'retrieve', 'retrograde', 'retrogress', 'retrospect',
         'retrospective', 'revamp', 'revelation', 'revelry', 'revenge', 'revenue', 'reverberant', 'reverberate',
         'reverence', 'reverent', 'reverie', 'reverse', 'reversion', 'revile', 'revitalize', 'revocable', 'revocation',
         'revoke', 'revolt', 'revolting', 'rhapsodize', 'rhapsody', 'rhetoric', 'rhinestone', 'rhubarb', 'rhythmic',
         'ribald', 'rickety', 'rigidity', 'rigmarole', 'rigorous', 'ringlet', 'riotous', 'risible', 'risque', 'ritual',
         'riveting', 'rivulet', 'robust', 'rodent', 'roguish', 'rollicking', 'rookie', 'rooster', 'roster', 'rotary',
         'rotund', 'roundabout', 'royalty', 'rubbery', 'rubble', 'rubicund', 'rucksack', 'rudder', 'rudimentary',
         'rudiments', 'rueful', 'ruffian', 'ruffle', 'ruminant', 'ruminate', 'ruminative', 'rummage', 'rumple',
         'rumpus', 'rupture', 'rustic', 'rusticate', 'rustler', 'sabotage', 'saccharin', 'sachet', 'sacrament',
         'sacred', 'sacrilegious', 'sacrosanct', 'saddle', 'safari', 'safeguard', 'sagacious', 'sagacity', 'salacious',
         'salacity', 'salient', 'saliferous', 'saliva', 'sallow', 'salmon', 'salubrious', 'salutary', 'salutation',
         'salvage', 'salvation', 'sampler', 'sanatorium', 'sanctimonious', 'sanction', 'sanctuary', 'sanctum',
         'sangfroid', 'sanguinary', 'sanguine', 'sanitary', 'sanitation', 'sanity', 'sapience', 'sapient', 'sapless',
         'sapling', 'sapphire', 'sarcasm', 'sarcastic', 'sardonic', 'sartorial', 'satanic', 'satiate', 'satiety',
         'satiny', 'satire', 'satirical', 'saturnalia', 'saturnine', 'saunter', 'savage', 'savanna', 'savant',
         'sawdust', 'scabbard', 'scabrous', 'scaffold', 'scalding', 'scalpel', 'scamper', 'scandal', 'scandalous',
         'scared', 'scathe', 'scathing', 'scavenge', 'scavenger', 'scenario', 'sceptical', 'sceptre', 'schematic',
         'schematize', 'scheme', 'schism', 'schismatic', 'schizophrenia', 'schooner', 'scintilla', 'scintillate',
         'scintillating', 'scorch', 'scorching', 'scorpion', 'scotch', 'scourge', 'scraggy', 'scramble', 'scrape',
         'scrawl', 'screed', 'screwdriver', 'scribble', 'scripture', 'scroll', 'scrooge', 'scruffy', 'scrumptious',
         'scrunch', 'scruple', 'scrupulous', 'scrutinize', 'scuffle', 'sculpt', 'scurrilous', 'scurry', 'scurvy',
         'scuttle', 'scythe', 'seafaring', 'seamstress', 'searing', 'seascape', 'seasoning', 'secateurs', 'secede',
         'secession', 'seclude', 'secluded', 'seclusion', 'seclusive', 'secretarial', 'secrete', 'sectarian', 'secular',
         'sedate', 'sedative', 'sedentary', 'sediment', 'sedition', 'seditious', 'seduce', 'seductive', 'sedulous',
         'seedling', 'seethe', 'segment', 'segregate', 'seismic', 'self-assertion', 'self-possession', 'sellotape',
         'semblance', 'seminal', 'seminary', 'senescent', 'seneschal', 'senile', 'senility', 'sensation', 'sensational',
         'sensual', 'sensuality', 'sententious', 'sentient', 'sentry', 'sepsis', 'septic', 'sepulcher', 'sepulchral',
         'sequacious', 'sequential', 'sequester', 'sequestrate', 'seraphic', 'serenade', 'serendipity', 'sermonize',
         'serpentine', 'serrated', 'servile', 'severance', 'sextant', 'shabby', 'shackle', 'shallop', 'shambles',
         'shanty', 'shareholder', 'shavings', 'shears', 'sheath', 'shelve', 'sheriff', 'shibboleth', 'shiftless',
         'shimmer', 'shindy', 'shingle', 'shipshape', 'shipwright', 'shoddy', 'shopsoiled', 'short-range', 'shovel',
         'showpiece', 'shrewd', 'shriek', 'shrill', 'shrine', 'shrink', 'shrivel', 'shroud', 'shuffle', 'shyster',
         'sibilant', 'sibling', 'sibylline', 'sidereal', 'sidesplitting', 'sifter', 'simian', 'simile', 'simper',
         'simulate', 'simulated', 'simultaneous', 'sinecure', 'sinewy', 'singularity', 'sinister', 'sinuous', 'sizzler',
         'skeptical', 'sketchy', 'skewer', 'skillet', 'skimpy', 'skinflint', 'skirmish', 'skulduggery', 'skyrocket',
         'slacken', 'slacker', 'slanderous', 'slapdash', 'slaver', 'sledgehammer', 'sleight', 'slither', 'sliver',
         'slobber', 'sloppy', 'slough', 'sloven', 'slovenly', 'sluggard', 'sluggish', 'sluice', 'slumber', 'slumberous',
         'smarmy', 'smashing', 'smattering', 'smirch', 'smithereens', 'smolder', 'smother', 'smudge', 'smuggle',
         'smutty', 'snappish', 'snappy', 'snarled', 'snatch', 'snazzy', 'sneaking', 'snigger', 'snobbish', 'snooty',
         'snowdrift', 'snuggle', 'soaked', 'sobriety', 'sobriquet', 'socialite', 'sodden', 'sojourn', 'solace',
         'solder', 'solecism', 'solemnity', 'solicit', 'solicitation', 'solicitous', 'solidarity', 'soliloquy',
         'solitary', 'solitude', 'solvency', 'solvent', 'somatic', 'somber', 'somnolent', 'sonata', 'sonority',
         'sonorous', 'sophism', 'sophisticated', 'sophistry', 'soporific', 'soprano', 'sorcery', 'sordid', 'sourpuss',
         'souvenir', 'sovereign', 'sovereignty', 'spacious', 'spangle', 'spanking', 'sparing', 'sparkle', 'sparse',
         'spartan', 'spasmodic', 'spatchcock', 'spatula', 'specifics', 'specimen', 'speciosity', 'specious',
         'spectacular', 'specter', 'spectral', 'spectrum', 'speculate', 'speculation', 'speleology', 'spellbind',
         'spelunker', 'spendthrift', 'sphagnum', 'sphinx', 'spindly', 'spineless', 'spinney', 'spinster', 'spiral',
         'splashy', 'spleenish', 'splendid', 'splendor', 'splenetic', 'splice', 'splint', 'splinter', 'splurge',
         'spongy', 'spontaneity', 'spontaneous', 'sporadic', 'sprain', 'sprawl', 'sprightly', 'sprinkler', 'sprinkling',
         'sprint', 'sprout', 'spruce', 'spurious', 'squalid', 'squalor', 'squander', 'squash', 'squelch', 'staccato',
         'stagger', 'staggering', 'stagnant', 'stalemate', 'stalwart', 'stamina', 'stammer', 'stance', 'stanch',
         'standoffish', 'stanza', 'staple', 'stapler', 'starchy', 'star-crossed', 'static', 'stationary', 'stationery',
         'statuary', 'statuette', 'stature', 'status', 'statute', 'statutory', 'steeple', 'stench', 'stencil',
         'stenography', 'stentorian', 'stereotype', 'sterile', 'sterilize', 'stethoscope', 'stickler', 'sticky',
         'stigmatize', 'stiletto', 'stilted', 'stimulant', 'stimulus', 'stingy', 'stipend', 'stipple', 'stipulate',
         'stipulation', 'stitch', 'stockade', 'stocky', 'stodge', 'stodgy', 'stoicism', 'stolid', 'stomach',
         'stonewall', 'storehouse', 'stouthearted', 'stowaway', 'strained', 'strait', 'straitened', 'straits',
         'stranded', 'strangulation', 'stratagem', 'stratify', 'stratum', 'streak', 'strenuous', 'striated',
         'stricture', 'stride', 'stridency', 'strident', 'stridulate', 'strife', 'striking', 'stringent', 'stripe',
         'stripling', 'stroll', 'strolling', 'stuffy', 'stunning', 'stuntman', 'stupefy', 'stupendous', 'stupor',
         'sturdy', 'stutter', 'stymie', 'styptic', 'subcutaneous', 'subdue', 'subjugate', 'sublimate', 'sublime',
         'subliminal', 'submerge', 'submission', 'submissive', 'subordinate', 'suborn', 'subpoena', 'subscribe',
         'subservient', 'subside', 'subsidiary', 'subsidy', 'substantiate', 'substantive', 'substitute', 'substratum',
         'subsume', 'subterfuge', 'subterranean', 'subtlety', 'subvention', 'subversive', 'subvert', 'succinct',
         'succor', 'succubus', 'succulent', 'succumb', 'suffice', 'sufficient', 'suffocate', 'suffrage', 'suffuse',
         'suggestible', 'suitor', 'sullen', 'sultry', 'summarily', 'sumptuous', 'sunder', 'sundry', 'superannuated',
         'superb', 'supercilious', 'superficial', 'superfluous', 'superimpose', 'superintend', 'superlative',
         'supernal', 'supersede', 'superstition', 'supine', 'supplant', 'supple', 'supplement', 'supplicant',
         'supplicate', 'supposition', 'suppurate', 'surefire', 'surfeit', 'surmise', 'surmount', 'surplus',
         'surreptitious', 'surrogate', 'susceptibilities', 'susceptible', 'suspense', 'sustain', 'sustained',
         'sustenance', 'suture', 'svelte', 'swagger', 'swarthy', 'sweltering', 'swerve', 'swindle', 'sycophant',
         'sycophantic', 'syllabus', 'symbiosis', 'symmetrical', 'symmetry', 'symposium', 'synapse', 'synchronize',
         'synchronous', 'syncopate', 'synonymous', 'synopsis', 'synoptic', 'synthetic', 'syringe', 'tableau',
         'tableland', 'taciturn', 'tactful', 'tactic', 'tactile', 'tadpole', 'tailwind', 'taking', 'talebearer',
         'talisman', 'tambourine', 'tamper', 'tangent', 'tangential', 'tangible', 'tanner', 'tantalize', 'tantamount',
         'tantrum', 'tapestry', 'tariff', 'tarnish', 'tarpaulin', 'tassel', 'tattered', 'tattle', 'tautological',
         'tawdry', 'taxonomy', 'technocrat', 'tedious', 'tedium', 'teetotal', 'telepathy', 'temerity', 'temper',
         'temperamental', 'temperance', 'temperate', 'tempest', 'tempestuous', 'temporal', 'temporary', 'temporize',
         'temptation', 'tenable', 'tenacious', 'tenacity', 'tendentious', 'tender', 'tenderfoot', 'tentative',
         'tenterhooks', 'tenuous', 'tenure', 'terminable', 'terminate', 'terminology', 'terminus', 'termite',
         'terpsichorean', 'terrace', 'terrain', 'terrapin', 'terrestrial', 'testament', 'testify', 'testimonial',
         'testimony', 'texture', 'thatch', 'theatrical', 'theism', 'theocracy', 'theology', 'therapeutic', 'therapy',
         'thesaurus', 'thespian', 'thicket', 'thrall', 'thrash', 'threadbare', 'threnody', 'thrifty', 'throaty',
         'throng', 'throttle', 'thrust', 'thwart', 'tickler', 'tiddler', 'timber', 'timbre', 'timely', 'timorous',
         'tinder', 'tirade', 'titanic', 'titillate', 'titivate', 'titular', 'tonality', 'topography', 'topple',
         'topsoil', 'tornado', 'torpid', 'torpor', 'torque', 'torrid', 'tortuous', 'torture', 'totalitarian',
         'totality', 'totter', 'touchy', 'toupee', 'tournament', 'tourniquet', 'tousle', 'towering', 'tractable',
         'traction', 'traduce', 'tragedienne', 'traitor', 'trajectory', 'trammel', 'trample', 'tranquil',
         'tranquillizer', 'transaction', 'transcend', 'transcendence', 'transcendental', 'transcribe', 'transfigure',
         'transform', 'transfuse', 'transgress', 'transient', 'transition', 'transitory', 'translucent', 'transmit',
         'transmogrify', 'transmute', 'transparent', 'transpire', 'trapezium', 'trauma', 'traumatic', 'travail',
         'travelogue', 'traverse', 'travesty', 'treacherous', 'treachery', 'treacle', 'treadmill', 'treason',
         'treatise', 'tremendous', 'tremor', 'tremulous', 'trench', 'trenchant', 'trepidation', 'trespass', 'tresses',
         'tribulation', 'tribunal', 'tributary', 'tribute', 'trickery', 'trickle', 'trifle', 'trigger', 'trinket',
         'trivia', 'trivial', 'troglodyte', 'trophy', 'trounce', 'troupe', 'trowel', 'truancy', 'truculence',
         'truculent', 'trudge', 'truism', 'trumpery', 'truncate', 'truncheon', 'tugboat', 'tumultuous', 'turbid',
         'turbulent', 'turgid', 'turmoil', 'turpitude', 'turquoise', 'turret', 'tussle', 'tutelage', 'tutelary',
         'tuxedo', 'twaddle', 'twinge', 'tycoon', 'typhoid', 'tyrannical', 'tyrant', 'ubiquitous', 'ulcerate',
         'ulterior', 'ultimate', 'ultramundane', 'umbrage', 'umpire', 'umpteen', 'unabashed', 'unadvised', 'unaffected',
         'unalloyed', 'unanimous', 'unassuming', 'unavailing', 'unbidden', 'uncanny', 'uncharted', 'uncommitted',
         'unconscionable', 'uncouth', 'unctuous', 'undaunted', 'underhanded', 'underling', 'undermine', 'underpin',
         'underplay', 'undesirable', 'undulate', 'unearth', 'unexampled', 'unfailing', 'unfathomed', 'unfettered',
         'unflappable', 'unfounded', 'ungainly', 'unguarded', 'unguent', 'unhinge', 'unicorn', 'unimpeachable',
         'unkempt', 'unprovoked', 'unravel', 'unruly', 'unscathed', 'unscrupulous', 'unseemly', 'unspotted',
         'unstudied', 'untoward', 'unversed', 'unwieldy', 'unwitting', 'upbraid', 'upheaval', 'uphold', 'upholstery',
         'upstage', 'upstart', 'upsurge', 'upswing', 'uptake', 'uptight', 'urbane', 'ursine', 'usurious', 'utensil',
         'utilitarian', 'utilize', 'utopian', 'uxorious', 'vacancy', 'vacate', 'vaccination', 'vaccine', 'vacillate',
         'vacuity', 'vacuous', 'vagabond', 'vagary', 'vainglorious', 'valediction', 'valetudinarian', 'valiant',
         'validate', 'valour', 'vampire', 'vandalism', 'vandalize', 'vanguard', 'vanilla', 'vanity', 'vanquish',
         'variability', 'variance', 'variegated', 'varnish', 'vascular', 'vassal', 'vegetate', 'vegetation', 'vehement',
         'vehicle', 'velocity', 'venality', 'vendetta', 'vendor', 'veneer', 'venerate', 'vengeance', 'venial',
         'venison', 'ventilate', 'veracious', 'veracity', 'verbiage', 'verbose', 'verbosity', 'verdant', 'verdict',
         'verdigris', 'verify', 'verisimilitude', 'vermin', 'vernacular', 'vernal', 'versed', 'vertebrate', 'vertex',
         'vertical', 'vertiginous', 'vertigo', 'vessel', 'vestment', 'vesture', 'veterinary', 'vexation', 'viable',
         'viaduct', 'viands', 'vibrancy', 'vibrant', 'vicarious', 'vicelike', 'vicinity', 'vicious', 'vicissitudes',
         'victuals', 'vigilant', 'vilify', 'villainous', 'villein', 'vindicate', 'vindication', 'vindictive',
         'vinegared', 'vintner', 'virile', 'virility', 'virtuosity', 'virtuoso', 'virulent', 'visage', 'viscosity',
         'viscous', 'vitiate', 'vitriolic', 'vituperate', 'vituperative', 'vivacious', 'vocalist', 'vociferate',
         'vociferous', 'volatile', 'volition', 'volubility', 'voluminous', 'voluptuary', 'voluptuous', 'voracious',
         'voracity', 'vortex', 'votary', 'voyeur', 'vulgar', 'vulgarity', 'vulnerable', 'vulpine', 'waddle', 'waffle',
         'waggish', 'wainscot', 'wallop', 'wallow', 'walrus', 'wanderlust', 'wangle', 'wanton', 'warden', 'wardrobe',
         'warfare', 'warmonger', 'warrant', 'washout', 'waspish', 'wastrel', 'watershed', 'weasel', 'whacked',
         'wheedle', 'wherry', 'whimper', 'whimsical', 'whimsy', 'whisper', 'whittle', 'wholesale', 'wiggle', 'wiliness',
         'willful', 'willow', 'willowy', 'wimple', 'winding', 'winnow', 'winsome', 'withdraw', 'withdrawn', 'wither',
         'wizened', 'woeful', 'wraith', 'wrangle', 'wreathe', 'wreckage', 'wrench', 'wrinkle', 'xenophobia',
         'xerophyte', 'yeoman', 'yielding', 'zealot', 'zealous', 'zenith', 'zephyr', 'zygote']
size = len(words)


def getPart(word):
    while(True):
        size = random.randint(3, 5)
        if len(word) < size + 2:
            size = 3
        index = random.randint(1, len(word) - size - 1)
        print(word[index:index + size])
        input()
        print(word)

i = random.randint(0, size)
getPart(words[i])
